# Generated by Django 4.2.30 on 2026-04-18 18:39

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='RateLimitViolation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip', models.GenericIPAddressField(db_index=True, unique=True)),
                ('violation_count', models.PositiveIntegerField(default=1)),
                ('first_violation', models.DateTimeField()),
                ('last_violation', models.DateTimeField()),
            ],
            options={
                'verbose_name': 'Rate Limit Violation',
                'ordering': ['-last_violation'],
            },
        ),
        migrations.CreateModel(
            name='RequestLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip', models.GenericIPAddressField(db_index=True)),
                ('path', models.CharField(max_length=500)),
                ('method', models.CharField(choices=[('GET', 'GET'), ('POST', 'POST'), ('PUT', 'PUT'), ('PATCH', 'PATCH'), ('DELETE', 'DELETE'), ('OPTIONS', 'OPTIONS')], db_index=True, max_length=10)),
                ('status_code', models.PositiveSmallIntegerField(db_index=True, null=True)),
                ('response_time_ms', models.PositiveIntegerField(null=True)),
                ('user_agent', models.CharField(blank=True, max_length=500)),
                ('country_code', models.CharField(blank=True, db_index=True, max_length=2)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
            ],
            options={
                'verbose_name': 'Request Log',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['created_at', 'status_code'], name='security_re_created_3b17a2_idx'), models.Index(fields=['ip', 'created_at'], name='security_re_ip_44460f_idx')],
            },
        ),
        migrations.CreateModel(
            name='BlockedIP',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip', models.GenericIPAddressField(db_index=True, unique=True)),
                ('reason', models.TextField(blank=True)),
                ('is_permanent', models.BooleanField(default=True)),
                ('expires_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('blocked_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='blocked_ips', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Blocked IP',
                'verbose_name_plural': 'Blocked IPs',
                'ordering': ['-created_at'],
            },
        ),
    ]
