# Generated by Django 4.2.30 on 2026-04-18 19:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('security', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SecurityConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rate_limit_requests', models.PositiveIntegerField(default=120, help_text='Max requests per IP per window')),
                ('rate_limit_window', models.PositiveIntegerField(default=60, help_text='Window size in seconds')),
                ('auto_block_threshold', models.PositiveIntegerField(default=10, help_text='Violations before auto-block')),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Security Config',
            },
        ),
    ]
