# Generated by Django 4.2.30 on 2026-04-18 19:45

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('security', '0002_securityconfig'),
    ]

    operations = [
        migrations.CreateModel(
            name='BlockedDevice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('device_signature', models.CharField(db_index=True, max_length=64, unique=True)),
                ('ip', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.TextField(blank=True)),
                ('reason', models.TextField(blank=True)),
                ('is_permanent', models.BooleanField(default=True)),
                ('expires_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Blocked Device',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddField(
            model_name='ratelimitviolation',
            name='device_signature',
            field=models.CharField(db_index=True, default='', max_length=64, unique=True),
        ),
        migrations.AddField(
            model_name='ratelimitviolation',
            name='user_agent',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='requestlog',
            name='device_signature',
            field=models.CharField(blank=True, db_index=True, max_length=64),
        ),
        migrations.AlterField(
            model_name='ratelimitviolation',
            name='ip',
            field=models.GenericIPAddressField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='securityconfig',
            name='rate_limit_requests',
            field=models.PositiveIntegerField(default=120, help_text='Max requests per device per window'),
        ),
        migrations.AddIndex(
            model_name='requestlog',
            index=models.Index(fields=['device_signature', 'created_at'], name='security_re_device__c3daaf_idx'),
        ),
        migrations.AddField(
            model_name='blockeddevice',
            name='blocked_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='blocked_devices', to=settings.AUTH_USER_MODEL),
        ),
    ]
