# Generated by Django 4.2.30 on 2026-04-17 19:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('site_config', '0002_herocontent'),
    ]

    operations = [
        migrations.CreateModel(
            name='ArtistProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='Beatha Theonest', max_length=255)),
                ('location', models.CharField(default='Arusha, Tanzania', max_length=255)),
                ('photo', models.ImageField(blank=True, null=True, upload_to='artist/')),
                ('biography', models.TextField(blank=True, default='')),
                ('story', models.TextField(blank=True, default='')),
                ('philosophy', models.TextField(blank=True, default='')),
                ('statement', models.TextField(blank=True, default='')),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Artist Profile',
                'verbose_name_plural': 'Artist Profile',
                'db_table': 'site_artist_profile',
            },
        ),
        migrations.CreateModel(
            name='Exhibition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_label', models.CharField(max_length=50)),
                ('title', models.CharField(max_length=255)),
                ('location', models.CharField(blank=True, default='', max_length=255)),
                ('order', models.PositiveIntegerField(db_index=True, default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Exhibition',
                'verbose_name_plural': 'Exhibitions',
                'db_table': 'site_exhibitions',
                'ordering': ['order', '-created_at'],
            },
        ),
    ]
