# Generated by Django 4.2.30 on 2026-04-20 11:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('site_config', '0003_add_artist_profile_and_exhibitions'),
    ]

    operations = [
        migrations.AddField(
            model_name='landinghero',
            name='favicon',
            field=models.ImageField(blank=True, null=True, upload_to='favicons/'),
        ),
    ]
