# Generated by Django 4.2.30 on 2026-04-12 11:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auction',
            name='bid_increment',
            field=models.DecimalField(decimal_places=2, default=1.0, help_text='Minimum amount each new bid must exceed the current price by.', max_digits=15),
        ),
        migrations.AlterField(
            model_name='auction',
            name='reserve_price',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Minimum price to complete the sale. Optional.', max_digits=15, null=True),
        ),
    ]
