# Generated by Django 4.2.30 on 2026-05-01 15:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0004_alter_auction_bid_increment_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='AuctionImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='auction_images/')),
                ('is_primary', models.BooleanField(db_index=True, default=False)),
                ('order', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('auction', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='auctions.auction')),
            ],
            options={
                'db_table': 'auction_images',
                'ordering': ['-is_primary', 'order', 'created_at'],
            },
        ),
    ]
